apiVersion: apps/v1
kind: Deployment 
metadata:
 name: nginxpod
 labels:
   app: nginx
spec:
  replicas: 1
  selector:
   matchLabels: 
     app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
     containers:
     - name: nginxc
       image: nginx:1.14.2
       ports: 
       - containerPort: 80
         protocol: T
